version: '2'
services:
  db:
    build:
      context: ./sentinel-postgres/
      dockerfile: ./Dockerfile
    restart: always
    hostname: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=mydb  
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  mongodb:
    image: mongo
    restart: always
    hostname: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
  backend:
    build:
      context: ./backend_v2/
      dockerfile: ./Dockerfile
    hostname: backend
    environment:
      - DB_URL=db
      - PROXY_URL=openshift-api-fetcher:5555/
    depends_on:
      - db
    restart: always
    ports:
      - '8080:8080'
  openshift-api-fetcher:
    build:
      context: ./openshift-api-fetcher/
      dockerfile: ./Dockerfile
    hostname: openshift-api-fetcher
    restart: always
    environment:
      - OPENSHIFT_TOKEN=eyJhbGciOiJSUzI1NiIsImtpZCI6ImZ5NzBxYl9YbzBGdk85aDVwbkhoYXE2MmxpcHo0bmF0VkVpbXJTMUh3QjAifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6InJvLWFwaS10b2tlbi1zMnduZyIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJyby1hcGkiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiJmZTE5NTVkMi04YTNkLTQxY2YtODBiYi1kNGUxYWFhODJiNWMiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6ZGVmYXVsdDpyby1hcGkifQ.ZyA97_xkfZWmyGO2Ss7_HCBd8osH2MeMZxxEnui7w5KJf1I77eSfJiNG7EPYJ5fZxPmQOVqDoikv0WobZazws9We_WoeCL7lA6zrik0L8DkCXdL9fRhI0AGyUlGmG79eUW8C0AZwkZoosRvK6U8kprEJBhwVRQuYKP80TTdXu1Vb4wEe4TX3ho-M6z8CgKyW1u3yLCft9Zd0jaf-svXFVhU7I3Bm9-vFrafIURlI_2JA-HhXIquRSxFkL28n0kzVWFQP9jqCAu_L7Xmryx78vm1s41lgza2hp-D_zkcNd3dJnlJIGxxSHoxInZuNHrqDGRKDKWMq3pQfWxlsExFlNEPYeMDyF66oQn2UcwzlzFfmC8mkF6Xw0aVjGT3zCXBxJPVZuxe9k01XOXJQ8ukH7NR7Cf-p_BuwAws-qKmZHBWjtHsgd4f2DhZFTT5hXlqD411dT_IOjWZvbMT1A0SVidkk6mW3GB0rsoQpUClvuL_u1eekKKEB-SMFWl2Jce7nqiRd_0Aash5_nStEG9zqr2NsA9U7deMWuV_5_SmtCdzd7J9dmFJhFAqFQrU3bnsI5Hqv_yBSzVGDAGr7YmXzKneFpDoTOix4KjCQ0-gUzV8mPcH3yYeH-gIPFCWGK60ZIhCMXPPmpr_l9dsVjZSc3EmfcKOHTO8LcaF1W-vSILk
      - MONGODB_URL=mongodb
    depends_on:
      - backend
    ports:
      - '5555:5555'
  openshift-audit-todb:
    build:
      context: ./openshift-audit-todb/
      dockerfile: ./Dockerfile
    hostname: openshift-audit-todb
    environment:
      - MONGODB_URL=mongodb
      - TOKEN=eyJhbGciOiJSUzI1NiIsImtpZCI6ImZ5NzBxYl9YbzBGdk85aDVwbkhoYXE2MmxpcHo0bmF0VkVpbXJTMUh3QjAifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6InJvLWFwaS10b2tlbi1zMnduZyIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJyby1hcGkiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiJmZTE5NTVkMi04YTNkLTQxY2YtODBiYi1kNGUxYWFhODJiNWMiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6ZGVmYXVsdDpyby1hcGkifQ.ZyA97_xkfZWmyGO2Ss7_HCBd8osH2MeMZxxEnui7w5KJf1I77eSfJiNG7EPYJ5fZxPmQOVqDoikv0WobZazws9We_WoeCL7lA6zrik0L8DkCXdL9fRhI0AGyUlGmG79eUW8C0AZwkZoosRvK6U8kprEJBhwVRQuYKP80TTdXu1Vb4wEe4TX3ho-M6z8CgKyW1u3yLCft9Zd0jaf-svXFVhU7I3Bm9-vFrafIURlI_2JA-HhXIquRSxFkL28n0kzVWFQP9jqCAu_L7Xmryx78vm1s41lgza2hp-D_zkcNd3dJnlJIGxxSHoxInZuNHrqDGRKDKWMq3pQfWxlsExFlNEPYeMDyF66oQn2UcwzlzFfmC8mkF6Xw0aVjGT3zCXBxJPVZuxe9k01XOXJQ8ukH7NR7Cf-p_BuwAws-qKmZHBWjtHsgd4f2DhZFTT5hXlqD411dT_IOjWZvbMT1A0SVidkk6mW3GB0rsoQpUClvuL_u1eekKKEB-SMFWl2Jce7nqiRd_0Aash5_nStEG9zqr2NsA9U7deMWuV_5_SmtCdzd7J9dmFJhFAqFQrU3bnsI5Hqv_yBSzVGDAGr7YmXzKneFpDoTOix4KjCQ0-gUzV8mPcH3yYeH-gIPFCWGK60ZIhCMXPPmpr_l9dsVjZSc3EmfcKOHTO8LcaF1W-vSILk
    depends_on:
      - mongodb
  front-end:
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
    hostname: font-end
    restart: always
    environment:
      - BACKEND=backend
    depends_on:
      - backend
    ports:
      - '80:80'
volumes:
  db:
    driver: local
  mongodb:
    driver: local