export const FETCH_NAMESPACES_PENDING = 'FETCH_NAMESPACES_PENDING';
export const FETCH_NAMESPACES_SUCCESS = 'FETCH_NAMESPACES_SUCCESS';
export const FETCH_NAMESPACES_ERROR = 'FETCH_NAMESPACES_ERROR';
export const FETCH_PODS_PENDING = 'FETCH_PODS_PENDING';
export const FETCH_PODS_SUCCESS = 'FETCH_PODS_SUCCESS';
export const FETCH_PODS_ERROR = 'FETCH_PODS_ERROR';