apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yaml
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: openshift-audit-todb
  name: openshift-audit-todb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: openshift-audit-todb
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.yaml
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: openshift-audit-todb
    spec:
      containers:
        - env:
            - name: MONGODB_URL
              value: mongodb
            - name: TOKEN
              value: eyJhbGciOiJSUzI1NiIsImtpZCI6ImZ5NzBxYl9YbzBGdk85aDVwbkhoYXE2MmxpcHo0bmF0VkVpbXJTMUh3QjAifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6InJvLWFwaS10b2tlbi1zMnduZyIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJyby1hcGkiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiJmZTE5NTVkMi04YTNkLTQxY2YtODBiYi1kNGUxYWFhODJiNWMiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6ZGVmYXVsdDpyby1hcGkifQ.ZyA97_xkfZWmyGO2Ss7_HCBd8osH2MeMZxxEnui7w5KJf1I77eSfJiNG7EPYJ5fZxPmQOVqDoikv0WobZazws9We_WoeCL7lA6zrik0L8DkCXdL9fRhI0AGyUlGmG79eUW8C0AZwkZoosRvK6U8kprEJBhwVRQuYKP80TTdXu1Vb4wEe4TX3ho-M6z8CgKyW1u3yLCft9Zd0jaf-svXFVhU7I3Bm9-vFrafIURlI_2JA-HhXIquRSxFkL28n0kzVWFQP9jqCAu_L7Xmryx78vm1s41lgza2hp-D_zkcNd3dJnlJIGxxSHoxInZuNHrqDGRKDKWMq3pQfWxlsExFlNEPYeMDyF66oQn2UcwzlzFfmC8mkF6Xw0aVjGT3zCXBxJPVZuxe9k01XOXJQ8ukH7NR7Cf-p_BuwAws-qKmZHBWjtHsgd4f2DhZFTT5hXlqD411dT_IOjWZvbMT1A0SVidkk6mW3GB0rsoQpUClvuL_u1eekKKEB-SMFWl2Jce7nqiRd_0Aash5_nStEG9zqr2NsA9U7deMWuV_5_SmtCdzd7J9dmFJhFAqFQrU3bnsI5Hqv_yBSzVGDAGr7YmXzKneFpDoTOix4KjCQ0-gUzV8mPcH3yYeH-gIPFCWGK60ZIhCMXPPmpr_l9dsVjZSc3EmfcKOHTO8LcaF1W-vSILk
          image: aradgonen98/sentinel-openshift-audit-todb
          name: openshift-audit-todb
          resources: {}
      hostname: openshift-audit-todb
      restartPolicy: Always
status: {}
